"""The stream-protocol frontend: the service on stdin/stdout for token-reading clients

The `clikernel` command connects a text-stream client to one gateway kernel. Requests and replies use a per-process delimiter. Input is not echoed. A `.` line acknowledges each accepted request before its result arrives.

Running the command without arguments creates a Python kernel and stops it on exit. `--kernel` attaches to an existing kernel and leaves it running. Ctrl-C during execution interrupts the kernel without ending the CLI process.

Docs: https://AnswerDotAI.github.io/clikernel/cli.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_cli.ipynb.

# %% auto #0
__all__ = ['fmt_error', 'serve_stream', 'main']

# %% ../nbs/02_cli.ipynb #25d654c4
import asyncio, secrets, signal, string, sys, termios, threading, traceback, tty
from fastcore.utils import *
from fastcore.script import call_parse
from .core import Gateway, default_gateway, resolve, session_defaults


# %% ../nbs/02_cli.ipynb #d8413fff
_ALPHANUM = string.ascii_letters + string.digits
_MULTILINE = "--"
_MARKER = "loading complete. session delimiter:"


def _new_delim(): return "--" + ''.join(secrets.choice(_ALPHANUM) for _ in range(5))


def _read_block(stdin, delim):
    lines = []
    for line in stdin:
        if line.rstrip("\n") == delim: return "".join(lines), None
        lines.append(line)
    return "", f"missing block terminator: {delim}"


def fmt_error(tag, text):
    nl = '' if text.endswith('\n') else '\n'
    return f"<{tag}>\n{text}{nl}</{tag}>"


# %% ../nbs/02_cli.ipynb #5649e04a
def _response(line, stdin, delim, execute):
    "Return (body, accepted), acknowledging accepted requests before execution."
    line = line.rstrip("\n")
    if line == delim: return fmt_error("protocol-error", "no multiline request is open: start one with a bare `--` line"), False
    if line == _MULTILINE:
        code, err = _read_block(stdin, delim)
        if err: return fmt_error("protocol-error", err), False
    elif line.startswith('%%'):
        return fmt_error("protocol-error",
            f"a %% cell magic needs a multiline request; send it as (flush-left):\n    --\n    {line}\n    <rest of cell>\n    {delim}"), False
    else: code = line
    print(".", flush=True)
    try: return execute(code), True
    except BaseException: return fmt_error("internal-error", traceback.format_exc()), True

# %% ../nbs/02_cli.ipynb #8c3decee
def _write_response(delim, body=None):
    if body: print(body, end='' if body.endswith('\n') else '\n', flush=True)
    print(delim, flush=True)


def _next_line(stdin):
    "Read one line; when not a TTY, SIGINT while idle means 'interrupt execution', not 'kill the worker', so ignore it"
    while True:
        try: return stdin.readline()
        except KeyboardInterrupt:
            if stdin.isatty(): raise


# %% ../nbs/02_cli.ipynb #bd6301f5
def _tty_clear(stream, idx, mask, cc=None):
    "Clear `mask` bits in termios field `idx` when `stream` is a TTY, with optional `cc` char overrides; returns state for `_restore_termios`"
    if not stream.isatty(): return None
    fd = stream.fileno()
    attrs = termios.tcgetattr(fd)
    new_attrs = attrs[:]
    new_attrs[idx] &= ~mask
    if cc:
        new_attrs[6] = attrs[6][:]
        for k, v in cc.items(): new_attrs[6][k] = v
    termios.tcsetattr(fd, termios.TCSADRAIN, new_attrs)
    return fd, attrs


def _restore_termios(state):
    if state: termios.tcsetattr(state[0], termios.TCSADRAIN, state[1])


# %% ../nbs/02_cli.ipynb #967cb6e3
def serve_stream(
    execute,          # Callable `code -> str`: run one request, returning the rendered response body
    info="",          # Server info announced between the loading lines (forwarded to mcp `instructions`)
    should_exit=None  # Callable checked after each request; truthy stops the worker
):
    "Serve delimiter-framed requests on stdin/stdout."
    # ONLCR off so protocol output stays bare LF; ECHO off (echoed input corrupts the protocol) and ICANON
    # off (canonical mode drops bytes past MAX_CANON with BEL spam; VMIN/VTIME make non-canonical reads
    # return per byte; ISIG stays on so ^C still interrupts)
    output_state = _tty_clear(sys.__stdout__, tty.OFLAG, termios.ONLCR)
    echo_state = _tty_clear(sys.stdin, tty.LFLAG, termios.ECHO | termios.ICANON, {termios.VMIN: 1, termios.VTIME: 0})
    delim = _new_delim()
    print(info, flush=True)
    print(f"<stream-protocol>\nOne-line request: send the line. Each response is an acknowledgement line '.' (request accepted, not complete), the rendered output, then the session delimiter line.\n"
        f"Multiline request (any multi-line cell, including %% cell magics), shown indented -- send it flush-left:\n"
        f"    --\n    <complete cell>\n    {delim}\n"
        f"No IPython prompt, no %cpaste, no invented terminators. A blank line is an empty request, so it doubles as an idle poll. Send 'exit' to end; a fresh process is the restart.\n</stream-protocol>", flush=True)
    print(_MARKER, flush=True)
    _write_response(delim)
    try:
        while True:
            line = _next_line(sys.stdin)
            if not line: break
            body, accepted = _response(line, sys.stdin, delim, execute)
            _write_response(delim, body)
            if accepted and should_exit and should_exit(): break
    finally:
        _restore_termios(echo_state)
        _restore_termios(output_state)

# %% ../nbs/02_cli.ipynb #8347cacd
_EXITS = ('exit', 'exit()', 'quit', 'quit()')

@call_parse
def main(
    host:str='',    # Gateway: empty for the local default, a `gateways.toml` name, or a URL
    kernel:str='',  # Kernel id (or unique prefix) to attach to; empty creates a kernel, stopped again on exit
):
    "The `clikernel` console script: the stream protocol over one gateway kernel"
    signal.signal(signal.SIGINT, signal.default_int_handler)
    print("please wait, loading...", flush=True)
    loop = asyncio.new_event_loop()
    threading.Thread(target=loop.run_forever, daemon=True).start()
    def run(coro): return asyncio.run_coroutine_threadsafe(coro, loop).result()
    async def _open():
        if not host: return await default_gateway()
        url, token, verify = resolve(host)
        return await Gateway(url, token, verify).initialize(session_defaults(local=False)), None
    g, child = run(_open())
    info = run(g.text('use_kernel', kernel=kernel) if kernel else g.text('create', kernel='py'))
    stop = False
    def execute(code):
        nonlocal stop
        if code.strip() in _EXITS:
            stop = True
            return ''
        fut = asyncio.run_coroutine_threadsafe(g.text('exec', code=code), loop)
        while True:
            try: return fut.result()
            except KeyboardInterrupt: asyncio.run_coroutine_threadsafe(g.call('interrupt'), loop)
    try: serve_stream(execute, info=info, should_exit=lambda: stop)
    finally:
        try: run(g.aclose())
        finally:
            try:
                if child: child.stop()
            finally: loop.call_soon_threadsafe(loop.stop)

