"""Gateway naming, startup delivery, and MCP sessions on rustygate gateways

[Rustygate](https://github.com/AnswerDotAI/rustygate) hosts kernels and serves MCP requests at `POST /mcp`. Clikernel runs alongside it for the duration of a conversation. It routes the LLM client's stdio MCP requests to gateways.

This module connects to those gateways. `gateways.toml` gives them names. `session_defaults` supplies kernel startup code and, for a local gateway, the conversation's working directory and environment. It combines `startup.py` and `inspectors.py` into source that can run on another machine.

`Gateway` represents one MCP session on one gateway. `default_gateway` connects to the local gateway or starts a child process if it cannot connect. The caller must stop any returned child. The MCP router does this when the conversation ends.

Rustygate tracks the session's current kernel and which kernels it created. Ending a session stops its autoclose kernels. It leaves other kernels running. Stopping an owned gateway process stops all kernels in that process.

Docs: https://AnswerDotAI.github.io/clikernel/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['DEFAULT_URL', 'cfg_dir', 'gateways', 'resolve', 'startup_src', 'session_defaults', 'Gateway', 'default_gateway']

# %% ../nbs/00_core.ipynb #2b3b7f4a
import os, tomllib, httpx
from fastcore.utils import *
from fastcore.xdg import xdg_config_home
from mcpmini.core import HTTPTransport, jreq
from rustygate.tools import start_gateway
from . import __version__

# %% ../nbs/00_core.ipynb #596419b8
DEFAULT_URL = 'http://127.0.0.1:8787'

def cfg_dir():
    "Return the clikernel configuration directory."
    return xdg_config_home()/'clikernel'

def gateways(cfgdir=None):
    "Read named gateways as `{name: {url, token | token_env, verify}}` from `gateways.toml`."
    p = (Path(cfgdir) if cfgdir else cfg_dir())/'gateways.toml'
    return tomllib.loads(p.read_text()).get('gateways', {}) if p.exists() else {}

def resolve(host='', cfgdir=None):
    "Resolve an empty host, URL, or configured gateway name to `(url, token, verify)`."
    if not host: return os.environ.get('CLIKERNEL_HOST', DEFAULT_URL), os.environ.get('CLIKERNEL_TOKEN'), True
    if '://' in host: return host, os.environ.get('CLIKERNEL_TOKEN'), True
    cfgdir = Path(cfgdir) if cfgdir else cfg_dir()
    g = gateways(cfgdir).get(host)
    if g is None: raise ValueError(f"unknown gateway {host!r}: not a URL, and not in {cfgdir/'gateways.toml'}")
    return g['url'], g.get('token') or os.environ.get(g.get('token_env','')) or None, g.get('verify', True)


# %% ../nbs/00_core.ipynb #0d846754
def _startup_src(src, path):
    "Wrap startup source with `__file__` set to its path during execution and deleted afterwards."
    return f'''__file__ = {str(path)!r}
try: exec(compile({src!r}, __file__, 'exec'))
finally: del __file__'''

# %% ../nbs/00_core.ipynb #3dbf4cb6
_INSP_RUNNER = r'''
import inspect as _clik_inspect
import sys as _clik_sys
from IPython.core.error import InputRejected
class RuleBlock(InputRejected):
    "Raise from an inspector to deliberately block a cell; any other inspector exception is a bug, and fails open"

class _ClikInspect:
    "Calls each inspector once per cell: 1-arg get the AST, 2-arg also the raw source"
    def __init__(self, fs): self.fs = fs
    def visit(self, tree):
        fr, n = _clik_sys._getframe(), 0
        while fr:
            n += fr.f_code.co_name == 'run_cell_async'
            fr = fr.f_back
        if n > 1: return tree  # nested run_cell: cell replayed by a tool (%nbrun etc.), not typed
        for f in self.fs:
            try:
                note = f(tree, _clik_src) if len(_clik_inspect.signature(f).parameters) > 1 else f(tree)
                if note: print(note, end='')
            except InputRejected: raise
            except Exception as e: print(f'inspector error (cell runs anyway): {e!r}')
        return tree

def _clik_stash(info):
    global _clik_src
    _clik_src = info.raw_cell

def _clik_install(src):
    ns = dict(RuleBlock=RuleBlock)
    exec(compile(src, 'inspectors.py', 'exec'), ns)
    fs = list(ns.get('inspectors') or [])
    if callable(ns.get('inspect')): fs.append(ns['inspect'])
    if fs:
        ip = get_ipython()
        ip.events.register('pre_run_cell', _clik_stash)
        ip.ast_transformers.append(_ClikInspect(fs))
_clik_src = ''
'''

def _inspector_setup(src):
    "Kernel-side source installing the inspectors defined in `src`; a load failure raises, failing the create call"
    return _INSP_RUNNER + f'\n_clik_install({src!r})'

# %% ../nbs/00_core.ipynb #1362e6ce
def startup_src(cfgdir=None):
    "Combine wrapped `startup.py` source with the inspector installer, in that order."
    d = Path(cfgdir) if cfgdir else cfg_dir()
    parts = []
    if (p := d/'startup.py').exists(): parts.append(_startup_src(p.read_text(), p))
    if (p := d/'inspectors.py').exists(): parts.append(_inspector_setup(p.read_text()))
    return '\n'.join(parts)

def session_defaults(cfgdir=None, quiet=False, local=True):
    "Return startup and quiet settings for rustygate initialization. Local sessions also include cwd and env."
    d = dict(startup=startup_src(cfgdir), quiet=quiet)
    if local:
        d['cwd'] = os.getcwd()
        d['env'] = dict(os.environ, CLIKERNEL_QUIET='1') if quiet else dict(os.environ)
    return d

# %% ../nbs/00_core.ipynb #10ed59fc
class Gateway:
    "Open an MCP session on rustygate, call its tools, and end the session with DELETE."
    def __init__(self,
        url,          # The gateway base URL, e.g. 'http://127.0.0.1:8787'
        token=None,   # Gateway auth token, sent as a bearer token
        verify=True,  # Verify TLS certificates?
    ):
        client = httpx.AsyncClient(verify=verify, timeout=httpx.Timeout(None, connect=10))
        self.url,self._id = url,0
        self.tr = HTTPTransport(f"{url.rstrip('/')}/mcp", token=token, http_client=client)

    async def rpc(self, method, **params):
        "Send a JSON-RPC request and return its result. Raise `RuntimeError` for protocol errors."
        self._id += 1
        r = await self.tr.send(jreq(method, self._id, **params))
        if 'error' in r: raise RuntimeError(f"{r['error']['code']}: {r['error']['message']}")
        return r['result']

    async def initialize(self, defaults=None):
        "Open the MCP session with `defaults` in the `rustygate` extension. Return self."
        await self.tr.start()
        self.info = await self.rpc('initialize', protocolVersion='2025-11-25', capabilities={},
            clientInfo=dict(name='clikernel', version=__version__), rustygate=defaults or {})
        self.tr.proto = self.info['protocolVersion']
        await self.tr.send(jreq('notifications/initialized'))
        return self

    async def tools(self): return (await self.rpc('tools/list'))['tools']
    async def call(self, name, **args): return await self.rpc('tools/call', name=name, arguments=args)

    async def text(self, name, **args):
        "Join a tool reply's text blocks. Raise `RuntimeError` for `isError` replies."
        r = await self.call(name, **args)
        t = ''.join(c.get('text','') for c in r['content'] if c['type'] == 'text')
        if r.get('isError'): raise RuntimeError(t)
        return t

    async def aclose(self):
        "Request session termination and close the HTTP connection."
        try: await self.tr.delete()
        finally: await self.tr.aclose()

# %% ../nbs/00_core.ipynb #0d054375
async def default_gateway(
    cfgdir=None,  # Config dir for `session_defaults` (the standard one if None)
    quiet=False,  # Keep startup output out of replies?
):
    "Return an initialized `Gateway` and its new child process, or None if it reused a gateway. The caller must stop any child."
    url, token, verify = resolve('', cfgdir)
    d = session_defaults(cfgdir, quiet)
    try: return await Gateway(url, token, verify).initialize(d), None
    except httpx.ConnectError:
        child = start_gateway()
        return await Gateway(child.url).initialize(d), child
