"""Connect to jupygate-hosted kernels and turn execution into concise text

clikernel is the LLM side of a two-process design: jupygate runs all the time and hosts the kernels; clikernel starts and stops with each conversation and holds nothing but a pointer. This module is the whole client: gateway resolution from `gateways.toml`, the concise-text rendering contract (ANSI-stripped, capped tracebacks), delivery of `startup.py` and `inspectors.py` into freshly created kernels, and `Client` — connect (create or attach), execute, interrupt, restart, stop, list. The MCP and CLI frontends are thin faces over `Client`; nothing here creates or kills a kernel except when asked."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['DEFAULT_URL', 'STATE_LOST', 'cfg_dir', 'gateways', 'resolve', 'render_outs', 'Client']

# %% ../nbs/00_core.ipynb #2b3b7f4a
import os, tomllib
from fastcore.utils import *
from fastcore.ansi import strip_ansi
from fastcore.nbio import render_text
from fastcore.xdg import xdg_config_home
from jupyasyncclient import JupyAsyncMultiKernelManager, DeadKernelError

# %% ../nbs/00_core.ipynb #596419b8
DEFAULT_URL = 'http://127.0.0.1:8787'

def cfg_dir():
    "The clikernel config directory"
    return xdg_config_home()/'clikernel'

def gateways(cfgdir=None):
    "Named gateways from `gateways.toml`: `{name: {url, token | token_env}}`"
    p = (Path(cfgdir) if cfgdir else cfg_dir())/'gateways.toml'
    return tomllib.loads(p.read_text()).get('gateways', {}) if p.exists() else {}

def resolve(host='', cfgdir=None):
    "`(url, token)` for `host`: empty = the default local gateway, a URL = itself, else a `gateways.toml` name"
    if not host: return os.environ.get('CLIKERNEL_HOST', DEFAULT_URL), os.environ.get('CLIKERNEL_TOKEN')
    if '://' in host: return host, os.environ.get('CLIKERNEL_TOKEN')
    g = gateways(cfgdir).get(host)
    if g is None: raise ValueError(f"unknown gateway {host!r}: not a URL, and not in {cfg_dir()/'gateways.toml'}")
    return g['url'], g.get('token') or os.environ.get(g.get('token_env','')) or None


# %% ../nbs/00_core.ipynb #b739b087
def _tb_line(l, maxlen):
    "One traceback line, capped at `maxlen`; `None` drops it (an over-long anchor line means nothing once cut). `File `/`Cell ` locations are exempt."
    if len(l) <= maxlen: return l
    if l.strip() and not (set(l) - set('~^ ')): return None
    if l.lstrip().startswith(('File ', 'Cell ')): return l
    return l[:maxlen] + '…'


def _trunc_tb(outputs, maxlen=120):
    "Cap over-long lines in error tracebacks: a cell magic's transformed source echoes its whole payload on one line. Locations survive whole, and so does the last chunk, which is the exception message in both IPython's format and the stdlib's."
    for o in outputs:
        if o.get("output_type") != "error": continue
        # Each chunk keeps its own identity: the renderer joins the list with newlines, so
        # flattening chunks into lines would silently drop the blank line between frames.
        # Strip ANSI before capping: the cap can sever an escape sequence, leaving an unstrippable fragment.
        tb = [strip_ansi(c) for c in o.get("traceback", [])]
        o["traceback"] = ["\n".join(l for l in (_tb_line(x, maxlen) for x in chunk.split("\n")) if l is not None)
            for chunk in tb[:-1]] + tb[-1:]
    return outputs

# %% ../nbs/00_core.ipynb #f70c7acd
def render_outs(outs):
    "Concise text for nbformat-style `outs`: cap tracebacks, render, strip ANSI"
    return strip_ansi(render_text(_trunc_tb(outs)))


# %% ../nbs/00_core.ipynb #0d846754
def _startup_src(src, path):
    "The startup file's source wrapped so `__file__` is bound to its path during the run, and absent after"
    return f'''__file__ = {str(path)!r}
try: exec(compile({src!r}, __file__, 'exec'))
finally: del __file__'''

# %% ../nbs/00_core.ipynb #3dbf4cb6
_INSP_RUNNER = r'''
import inspect as _clik_inspect
from IPython.core.error import InputRejected
class RuleBlock(InputRejected):
    "Raise from an inspector to deliberately block a cell; any other inspector exception is a bug, and fails open"

class _ClikInspect:
    "Calls each inspector once per cell: 1-arg get the AST, 2-arg also the raw source"
    def __init__(self, fs): self.fs = fs
    def visit(self, tree):
        for f in self.fs:
            try:
                note = f(tree, _clik_src) if len(_clik_inspect.signature(f).parameters) > 1 else f(tree)
                if note: print(note, end='')
            except InputRejected: raise
            except Exception as e: print(f'inspector error (cell runs anyway): {e!r}')
        return tree

def _clik_stash(info):
    global _clik_src
    _clik_src = info.raw_cell

def _clik_install(src):
    ns = dict(RuleBlock=RuleBlock)
    exec(compile(src, 'inspectors.py', 'exec'), ns)
    fs = list(ns.get('inspectors') or [])
    if callable(ns.get('inspect')): fs.append(ns['inspect'])
    if fs:
        ip = get_ipython()
        ip.events.register('pre_run_cell', _clik_stash)
        ip.ast_transformers.append(_ClikInspect(fs))
_clik_src = ''
'''

def _inspector_setup(src):
    "Kernel-side source installing the inspectors defined in `src`; a load failure raises, failing the create call"
    return _INSP_RUNNER + f'\n_clik_install({src!r})'

# %% ../nbs/00_core.ipynb #33b7bc28
STATE_LOST = 'NOTE: the kernel restarted with a fresh interpreter: all session state is lost (imports, variables, monkeypatches). Redo any setup the task still needs.'

class Client:
    "One conversation's connection: a gateway manager, and the current kernel"
    def __init__(self, cfgdir=None): self.cfgdir,self.mgr,self.kc,self.kid = cfgdir,None,None,None

    async def _use(self, mgr, kid):
        "Point at `kid` on `mgr`, dropping any previous ws (never the kernel)"
        if self.kc: await self.kc.aclose()
        if self.mgr is not None and self.mgr is not mgr: await self.mgr.aclose()
        self.mgr,self.kid,self.kc = mgr,kid,mgr.client(kid)
        self.kc.start_channels()
        await self.kc.wait_for_ready(timeout=30)

# %% ../nbs/00_core.ipynb #94497e4a
@patch
async def connect(self:Client, host='', kernel=''):
    "Connect to a gateway (create a kernel, or attach to `kernel` by id prefix); the pointer aims at it afterwards"
    url,tok = resolve(host, self.cfgdir)
    mgr = JupyAsyncMultiKernelManager(url, token=tok)
    ks = await mgr.list_kernels()   # verify reachability and auth now, loudly
    if kernel:
        kid = first(k['id'] for k in ks if k['id'].startswith(kernel))
        if not kid: raise ValueError(f'no kernel matching {kernel!r} on {url}: {[k["id"][:8] for k in ks]}')
        await self._use(mgr, kid)
        return f'connected to existing kernel {kid} on {url}'
    kw = dict(cwd=os.getcwd(), env=dict(os.environ)) if not host else {}   # the default gateway is local by definition: kernels start where, and as, the conversation lives (cwd and environment - so kernel-side tools that key state to the conversation, like llmdojo's doc-state, resolve it correctly)
    kid = await mgr.start_kernel(**kw)
    await self._use(mgr, kid)
    out = ''
    d = Path(self.cfgdir) if self.cfgdir else cfg_dir()
    if (p := d/'startup.py').exists(): out = await self.execute(_startup_src(p.read_text(), p))
    if (p := d/'inspectors.py').exists():
        res = await self.execute(_inspector_setup(p.read_text()))
        if res:   # a load failure is fatal: refusing to start beats running uninspected
            await self.mgr.shutdown_kernel(kid)
            self.kc,self.kid = None,None
            raise RuntimeError(f'inspectors.py failed to load; kernel stopped:\n{res}')
    return f'created kernel {kid} on {url}' + (f'\n{out}' if out.strip() else '')

@patch
async def execute_outs(self:Client, code):
    "Run `code` in the current kernel; nbformat-style output dicts (or a protocol note string)"
    if not self.kc: return 'no kernel: call `connect` first'
    try: return await self.kc.run(code)
    except DeadKernelError: return 'NOTE: the kernel process died. `connect` to create or attach to another.'

@patch
async def execute(self:Client, code):
    "Run `code` in the current kernel; concise rendered text of its outputs"
    r = await self.execute_outs(code)
    return r if isinstance(r, str) else render_outs(r)

# %% ../nbs/00_core.ipynb #1ef42fff
@patch
async def list_kernels(self:Client, host=''):
    "One line per kernel on the gateway (the current one if `host` is empty and connected)"
    if host or self.mgr is None:
        url,tok = resolve(host, self.cfgdir)
        mgr = JupyAsyncMultiKernelManager(url, token=tok)
        ks = await mgr.list_kernels()
        await mgr.aclose()
    else: ks = await self.mgr.list_kernels()
    if not ks: return 'no kernels'
    def _l(k): return f"{k['id']}  {k.get('execution_state','?')}  connections={k.get('connections','?')}" + ('  <- current' if k['id']==self.kid else '')
    return '\n'.join(_l(k) for k in ks)

@patch
async def stop(self:Client, kernel=''):
    "Stop a kernel by id prefix (the current one if empty): the only way anything is ever killed"
    if not self.mgr: return 'no gateway: call `connect` first'
    if not kernel and not self.kid: return 'no current kernel: pass an id from `list_kernels`'
    kid = self.kid if not kernel else first(k['id'] for k in await self.mgr.list_kernels() if k['id'].startswith(kernel))
    if not kid: return f'no kernel matching {kernel!r}'
    await self.mgr.shutdown_kernel(kid)
    if kid == self.kid:
        await self.kc.aclose()
        self.kc,self.kid = None,None
    return f'stopped kernel {kid}'

@patch
async def restart(self:Client):
    "Restart the current kernel: same id, fresh interpreter"
    if not self.kc: return 'no kernel: call `connect` first'
    await self.mgr.restart_kernel(self.kid)
    await self.kc.wait_for_ready(timeout=30)
    return STATE_LOST

@patch
async def interrupt(self:Client):
    "SIGINT the current kernel's running cell"
    if not self.kc: return 'no kernel: call `connect` first'
    await self.mgr.interrupt_kernel(self.kid)
    return 'interrupt sent'

@patch
async def aclose(self:Client):
    "Drop connections; kernels are left exactly as they are"
    if self.kc: await self.kc.aclose()
    if self.mgr: await self.mgr.aclose()
    self.mgr,self.kc,self.kid = None,None,None
