"""Connect to gateway-hosted kernels and turn execution into concise text

clikernel is the LLM side of a two-process design: a gateway ([rustygate](https://github.com/AnswerDotAI/rustygate)) runs all the time and hosts the kernels; clikernel starts and stops with each conversation and holds nothing but a pointer. This module is the whole client: gateway resolution from `gateways.toml`, the concise-text rendering contract (ANSI-stripped, capped tracebacks), delivery of `startup.py` and `inspectors.py` into freshly created kernels, and `Client` — connect (create or attach), execute, interrupt, restart, stop, list. The MCP and CLI frontends are thin faces over `Client`; nothing here creates or kills a kernel except when asked, and the one scoped kill is opt-in: a kernel created with `auto=True` belongs to its client, ended by that client's next `connect` or by the frontend on the way out.

Docs: https://AnswerDotAI.github.io/clikernel/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['DEFAULT_URL', 'MAXLEN', 'STATE_LOST', 'STATE_LOST_SETUP', 'cfg_dir', 'gateways', 'resolve', 'Client']

# %% ../nbs/00_core.ipynb #2b3b7f4a
import httpx, os, tomllib
from fastcore.utils import *
from fastcore.nbio import render_text
from fastcore.xdg import xdg_config_home
from jupyasyncclient import JupyAsyncMultiKernelManager, DeadKernelError

# %% ../nbs/00_core.ipynb #596419b8
DEFAULT_URL = 'http://127.0.0.1:8787'
MAXLEN = 180 # Most characters shown per displayed line

def cfg_dir():
    "The clikernel config directory"
    return xdg_config_home()/'clikernel'

def gateways(cfgdir=None):
    "Named gateways from `gateways.toml`: `{name: {url, token | token_env, verify}}`"
    p = (Path(cfgdir) if cfgdir else cfg_dir())/'gateways.toml'
    return tomllib.loads(p.read_text()).get('gateways', {}) if p.exists() else {}

def resolve(host='', cfgdir=None):
    "`(url, token, verify)` for `host`: empty = the default local gateway, a URL = itself, else a `gateways.toml` name"
    if not host: return os.environ.get('CLIKERNEL_HOST', DEFAULT_URL), os.environ.get('CLIKERNEL_TOKEN'), True
    if '://' in host: return host, os.environ.get('CLIKERNEL_TOKEN'), True
    g = gateways(cfgdir).get(host)
    if g is None: raise ValueError(f"unknown gateway {host!r}: not a URL, and not in {cfg_dir()/'gateways.toml'}")
    return g['url'], g.get('token') or os.environ.get(g.get('token_env','')) or None, g.get('verify', True)


# %% ../nbs/00_core.ipynb #0d846754
def _startup_src(src, path):
    "The startup file's source wrapped so `__file__` is bound to its path during the run, and absent after"
    return f'''__file__ = {str(path)!r}
try: exec(compile({src!r}, __file__, 'exec'))
finally: del __file__'''

# %% ../nbs/00_core.ipynb #3dbf4cb6
_INSP_RUNNER = r'''
import inspect as _clik_inspect
import sys as _clik_sys
from IPython.core.error import InputRejected
class RuleBlock(InputRejected):
    "Raise from an inspector to deliberately block a cell; any other inspector exception is a bug, and fails open"

class _ClikInspect:
    "Calls each inspector once per cell: 1-arg get the AST, 2-arg also the raw source"
    def __init__(self, fs): self.fs = fs
    def visit(self, tree):
        fr, n = _clik_sys._getframe(), 0
        while fr:
            n += fr.f_code.co_name == 'run_cell_async'
            fr = fr.f_back
        if n > 1: return tree  # nested run_cell: cell replayed by a tool (%nbrun etc.), not typed
        for f in self.fs:
            try:
                note = f(tree, _clik_src) if len(_clik_inspect.signature(f).parameters) > 1 else f(tree)
                if note: print(note, end='')
            except InputRejected: raise
            except Exception as e: print(f'inspector error (cell runs anyway): {e!r}')
        return tree

def _clik_stash(info):
    global _clik_src
    _clik_src = info.raw_cell

def _clik_install(src):
    ns = dict(RuleBlock=RuleBlock)
    exec(compile(src, 'inspectors.py', 'exec'), ns)
    fs = list(ns.get('inspectors') or [])
    if callable(ns.get('inspect')): fs.append(ns['inspect'])
    if fs:
        ip = get_ipython()
        ip.events.register('pre_run_cell', _clik_stash)
        ip.ast_transformers.append(_ClikInspect(fs))
_clik_src = ''
'''

def _inspector_setup(src):
    "Kernel-side source installing the inspectors defined in `src`; a load failure raises, failing the create call"
    return _INSP_RUNNER + f'\n_clik_install({src!r})'

# %% ../nbs/00_core.ipynb #33b7bc28
STATE_LOST = 'NOTE: the kernel restarted with a fresh interpreter: all session state is lost (imports, variables, monkeypatches). Redo any setup the task still needs.'
STATE_LOST_SETUP = 'NOTE: the kernel restarted with a fresh interpreter: startup.py has been re-run (its imports are back), but all other session state is lost (variables, monkeypatches, other imports). Redo what the task still needs.'

class Client:
    "One conversation's connection: a gateway manager, and the current kernel"
    def __init__(self, cfgdir=None): self.cfgdir,self.mgr,self.kc,self.kid,self.auto,self.made = cfgdir,None,None,None,False,False

    async def _use(self, mgr, kid):
        "Point at `kid` on `mgr`, dropping any previous ws (never the kernel)"
        if self.kc: await self.kc.aclose()
        if self.mgr is not None and self.mgr is not mgr: await self.mgr.aclose()
        self.mgr,self.kid,self.kc = mgr,kid,mgr.client(kid)
        self.kc.start_channels()
        await self.kc.wait_for_ready(timeout=30)

# %% ../nbs/00_core.ipynb #94497e4a
@patch
async def _setup(self:Client):
    "Deliver `startup.py` and `inspectors.py` to the current kernel, returning startup's output"
    out = ''
    d = Path(self.cfgdir) if self.cfgdir else cfg_dir()
    if (p := d/'startup.py').exists(): out = await self.execute(_startup_src(p.read_text(), p))
    if (p := d/'inspectors.py').exists():
        res = await self.execute(_inspector_setup(p.read_text()))
        if res:   # a load failure is fatal: refusing to run beats running uninspected
            await self.mgr.shutdown_kernel(self.kid)
            self.kc,self.kid,self.auto,self.made = None,None,False,False
            raise RuntimeError(f'inspectors.py failed to load; kernel stopped:\n{res}')
    return out

@patch
async def connect(self:Client, host='', kernel='', auto=False):
    "Connect to a gateway (create a kernel, or attach to `kernel` by id prefix); the pointer aims at it afterwards; `auto` marks a created kernel as client-scoped"
    note = ''
    if self.auto:   # scoped to this client: any new connect ends it, even one already dead
        try: await self.stop()
        except Exception as e:
            self.kc,self.kid,self.auto,self.made = None,None,False,False
            note = f'\nnote: stopping the auto kernel failed ({e})'
    url,tok,ver = resolve(host, self.cfgdir)
    mgr = JupyAsyncMultiKernelManager(url, token=tok, verify=ver)
    ks = await mgr.list_kernels()   # verify reachability and auth now, loudly
    if kernel:
        kid = first(k['id'] for k in ks if k['id'].startswith(kernel))
        if not kid: raise ValueError(f'no kernel matching {kernel!r} on {url}: {[k["id"][:8] for k in ks]}')
        await self._use(mgr, kid)
        self.made = False
        return f'connected to existing kernel {kid} on {url}' + note
    kw = dict(cwd=os.getcwd(), env=dict(os.environ)) if not host else {}   # the default gateway is local by definition: kernels start where, and as, the conversation lives (cwd and environment - so kernel-side tools that key state to the conversation, like llmdojo's doc-state, resolve it correctly)
    kid = await mgr.start_kernel(**kw)
    await self._use(mgr, kid)
    self.made = True
    out = await self._setup()
    self.auto = auto
    return f'created kernel {kid} on {url}' + (f'\n{out}' if out.strip() else '') + note

@patch
async def execute_outs(self:Client, code):
    "Run `code` in the current kernel; nbformat-style output dicts (or a protocol note string)"
    if not self.kc: return 'no kernel: call `connect` first'
    try: return await self.kc.run(code)
    except DeadKernelError: return 'NOTE: the kernel process died. `connect` to create or attach to another.'

@patch
async def execute(self:Client, code):
    "Run `code` in the current kernel; concise rendered text of its outputs"
    r = await self.execute_outs(code)
    return r if isinstance(r, str) else render_text(r, tb_maxlen=MAXLEN)

# %% ../nbs/00_core.ipynb #1ef42fff
@patch
async def list_kernels(self:Client, host=''):
    "One line per kernel on the gateway (the current one if `host` is empty and connected)"
    if host or self.mgr is None:
        url,tok,ver = resolve(host, self.cfgdir)
        mgr = JupyAsyncMultiKernelManager(url, token=tok, verify=ver)
        ks = await mgr.list_kernels()
        await mgr.aclose()
    else: ks = await self.mgr.list_kernels()
    if not ks: return 'no kernels'
    def _l(k): return f"{k['id']}  {k.get('execution_state','?')}  connections={k.get('connections','?')}" + ('  <- current' if k['id']==self.kid else '')
    return '\n'.join(_l(k) for k in ks)

@patch
async def stop(self:Client, kernel=''):
    "Stop a kernel by id prefix (the current one if empty): the only way anything is ever killed"
    if not self.mgr: return 'no gateway: call `connect` first'
    if not kernel and not self.kid: return 'no current kernel: pass an id from `list_kernels`'
    kid = self.kid if not kernel else first(k['id'] for k in await self.mgr.list_kernels() if k['id'].startswith(kernel))
    if not kid: return f'no kernel matching {kernel!r}'
    await self.mgr.shutdown_kernel(kid)
    if kid == self.kid:
        await self.kc.aclose()
        self.kc,self.kid,self.auto,self.made = None,None,False,False
    return f'stopped kernel {kid}'

@patch
async def restart(self:Client):
    "Restart the current kernel: same id, fresh interpreter; a kernel this client created gets `startup.py` and `inspectors.py` again"
    if not self.kc: return 'no kernel: call `connect` first'
    try: await self.mgr.restart_kernel(self.kid)
    except httpx.HTTPStatusError as e:
        if e.response.status_code != 404:
            return f'restart failed ({e.response.text}); the kernel is still listed: retry, `stop` it, or `connect` for a fresh one'
        old,kw = self.kid,{}
        await self.kc.aclose()
        if self.mgr.base_url == resolve('', self.cfgdir)[0]: kw = dict(cwd=os.getcwd(), env=dict(os.environ))
        await self._use(self.mgr, await self.mgr.start_kernel(**kw))
        self.made = True
        out = await self._setup()
        return f'kernel {old} was gone; created fresh kernel {self.kid}.\n' + STATE_LOST_SETUP + (f'\n{out}' if out.strip() else '')
    except httpx.TransportError as e:
        return f'restart did not complete ({type(e).__name__}): retry, or `connect` for a fresh kernel; check the gateway if this persists'
    await self.kc.wait_for_ready(timeout=30)
    if not self.made: return STATE_LOST
    out = await self._setup()
    return STATE_LOST_SETUP + (f'\n{out}' if out.strip() else '')

@patch
async def interrupt(self:Client):
    "SIGINT the current kernel's running cell"
    if not self.kc: return 'no kernel: call `connect` first'
    await self.mgr.interrupt_kernel(self.kid)
    return 'interrupt sent'

@patch
async def aclose(self:Client):
    "Drop connections; kernels are left exactly as they are"
    if self.kc: await self.kc.aclose()
    if self.mgr: await self.mgr.aclose()
    self.mgr,self.kc,self.kid = None,None,None
