"""Route stdio MCP requests to rustygate gateways

Claude Code starts `clikernel-mcp` for each conversation. Its `Router` accepts MCP messages over stdio and sends tool calls to rustygate gateways. Rustygate implements the tools. The router gets their schemas from the local gateway and adds `host` to `list_kernels`, `use_kernel`, and `create`.

Each host has a separate gateway session. The router remembers one current host for calls without an explicit `host`. It removes `host` before forwarding a call but preserves the JSON-RPC request id. Cancellation notifications also retain their original ids.

`main` runs the router and closes its gateway sessions on exit. Closing a session sends an HTTP DELETE. The gateway then stops the kernels that session created with autoclose. If the router started a child gateway, it stops that process too.

Docs: https://AnswerDotAI.github.io/clikernel/mcp.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_mcp.ipynb.

# %% auto #0
__all__ = ['HOST_PARAM', 'HOSTED', 'Router', 'main']

# %% ../nbs/01_mcp.ipynb #28c42902
import asyncio
from fastcore.utils import *
from fastcore.script import call_parse, store_true
from mcpmini.core import serve_stdio, jresp, jerr
from .core import Gateway, default_gateway, resolve, session_defaults
from . import __version__


# %% ../nbs/01_mcp.ipynb #76e2d782
HOST_PARAM = {'type': 'string', 'description': 'Gateway to target: a gateways.toml name, or empty for the default local gateway'}
HOSTED = ('list_kernels', 'use_kernel', 'create')

class Router:
    "Route stdio MCP to rustygate with one session per host and one current host."
    def __init__(self,
        cfgdir=None,  # Config dir for `session_defaults` and `gateways.toml` (the standard one if None)
        quiet=False,  # Keep startup output out of replies?
    ):
        self.cfgdir,self.quiet,self.sessions,self.cur,self.child = cfgdir,quiet,{},'',None

    async def session(self, host=''):
        "Return the session for `host`, initializing it on first use. Empty `host` selects the default local gateway."
        if host not in self.sessions:
            if host:
                url, token, verify = resolve(host, self.cfgdir)
                self.sessions[host] = await Gateway(url, token, verify).initialize(session_defaults(self.cfgdir, self.quiet, local=False))
            else: self.sessions[host], self.child = await default_gateway(self.cfgdir, self.quiet)
        return self.sessions[host]

    async def aclose(self):
        "Close all sessions and their autoclose kernels, then stop any owned gateway."
        try: results = await asyncio.gather(*(s.aclose() for s in self.sessions.values()), return_exceptions=True)
        finally:
            if self.child: self.child.stop()
        errors = [r for r in results if isinstance(r, BaseException)]
        if errors: raise BaseExceptionGroup('MCP session cleanup failed', errors)


# %% ../nbs/01_mcp.ipynb #79da6a3e
@patch
async def tools(self:Router):
    "Return the local gateway's tools with `host` added to `list_kernels`, `use_kernel`, and `create`."
    ts = await (await self.session()).tools()
    for t in ts:
        if t['name'] in HOSTED: t['inputSchema'].setdefault('properties', {})['host'] = dict(HOST_PARAM)
    return ts

@patch
async def dispatch(self:Router, msg, requester=None):
    "Answer initialization and ping locally. Forward tool calls to gateways."
    method,id = msg.get('method'), msg.get('id')
    try:
        if method == 'initialize':
            info = (await self.session()).info
            return jresp(id, dict(protocolVersion=msg['params'].get('protocolVersion', '2025-06-18'), capabilities=dict(tools={}),
                serverInfo=dict(name='clikernel', version=__version__), instructions=info.get('instructions')))
        if id is None:
            if method == 'notifications/cancelled': await (await self.session(self.cur)).tr.send(msg)
            return None
        if method == 'ping': return jresp(id, {})
        if method == 'tools/list': return jresp(id, dict(tools=await self.tools()))
        if method == 'tools/call':
            args = msg['params'].setdefault('arguments', {})
            has_host = 'host' in args
            host = args.pop('host', '') or ''
            s = await self.session(host if has_host else self.cur)
            if has_host and msg['params']['name'] in ('use_kernel', 'create'): self.cur = host
            return await s.tr.send(msg)
        return jerr(id, -32601, f'method not found: {method}')
    except Exception as e: return None if id is None else jerr(id, -32603, str(e))

# %% ../nbs/01_mcp.ipynb #3b90f0e8
@call_parse
def main(
    quiet:store_true=False,  # Keep startup output out of replies
):
    "Run `clikernel-mcp` as a stdio server."
    async def _main():
        router = Router(quiet=quiet)
        try: await serve_stdio(router)
        finally: await router.aclose()
    asyncio.run(_main())

