"""The MCP frontend: `Client` as tools on stdio

The frontend Claude Code launches per conversation. `mk_server` closes the tools over a `Client`, and `main` serves them on stdio through mcpmini. The server answers `initialize` without starting a kernel. The first `execute` auto-connects when needed. `connect` remains available for attaching, selecting another gateway, or creating a kernel that outlives the conversation. A kernel `input_request` becomes an MCP elicitation inside the same `execute` call. jupywire sends the elicitation response back to the requesting kernel.

Docs: https://AnswerDotAI.github.io/clikernel/mcp.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_mcp.ipynb.

# %% auto #0
__all__ = ['part2block', 'mk_server', 'main']

# %% ../nbs/01_mcp.ipynb #28c42902
import asyncio
from fastcore.utils import *
from fastcore.script import call_parse, store_true
from mcpmini.core import MCPServer, serve_stdio
from aidialog.dialog import Message
from aidialog.hist import output_parts, merge_media
from aidialog.msg_parts import PartType, data_url
from fastcore.nbio import render_text
from .core import Client, MAXLEN
from . import __version__


# %% ../nbs/01_mcp.ipynb #773d02aa
def part2block(p):
    "An MCP content block for aidialog `Part` `p`"
    if p.type != PartType.input_image: return dict(type='text', text=p.text)
    mime,b64 = data_url(p.text)
    return dict(type='image', data=b64, mimeType=mime)

# %% ../nbs/01_mcp.ipynb #76e2d782
def mk_server(c:Client):
    "An `MCPServer` whose tools close over `c`: connect, execute, and the lifecycle verbs"
    alock = asyncio.Lock()
    input_schema = dict(type='object', properties=dict(value=dict(type='string')), required=['value'])

    async def _input(msg):
        content = msg['content']
        if content.get('password'): raise RuntimeError('password prompts are not supported through MCP')
        r = await srv.elicit(content.get('prompt',''), input_schema)
        if r.get('action') != 'accept': raise RuntimeError(f"input {r.get('action','cancelled')}")
        return r['content']['value']

    async def connect(
        host:str='', # Gateway: empty for the local default, a `gateways.toml` name, or a URL
        kernel:str='', # Kernel id (or unique prefix) to attach to; empty creates a fresh kernel
    )->str:
        "Connect to a kernel. With `kernel`: attach to that existing kernel exactly as it is (nothing is run) - this is how a later conversation returns to live state, and how to reach a kernel someone else created. Without: create a fresh kernel, run the user's startup.py in it, and install their inspectors; the reply includes the new kernel's id (reusable in a later `connect`). Kernels made or attached this way persist until explicitly stopped: disconnecting, switching, and conversation end never kill them. (Connecting also immediately stops the auto kernel, if `execute` had created one.)"
        return await c.connect(host, kernel)

    async def execute(
        code:str, # Python/IPython code to run
    ):
        "Run `code` in the current kernel, keeping state across calls (imports, variables, monkeypatches, cached objects). With no kernel connected, one is auto-created first (default gateway, startup.py and inspectors run). An auto-created kernel is scoped to the conversation: it stops when the conversation ends or when `connect` moves elsewhere; use `connect` for a kernel that should outlive the conversation. Kernel input prompts use the MCP client's elicitation UI. Password prompts are refused. If the reply says the kernel died, `connect` again. Image outputs (plots etc.) come back as image blocks, resized to a token-friendly size, each preceded by its `<media id=...>` tag."
        pre = ''
        async with alock:
            if not c.kc:
                banner = await c.connect(auto=True)
                if not c.quiet: pre = banner + '\n'
        r = await c.execute_outs(code, on_stdin=_input)
        if isinstance(r, str): return pre + r
        res = merge_media(render_text(r, tb_maxlen=MAXLEN), output_parts(Message(msg_type='code', output=r)))
        if isinstance(res, str): return pre + res
        blocks = [part2block(p) for p in res]
        if pre: blocks = [dict(type='text', text=pre)] + blocks
        return dict(content=blocks, isError=False)

    async def list_kernels(
        host:str='', # Gateway to list; empty for the current one (or the default if not connected)
    )->str:
        "One line per kernel on the gateway: id, state, connection count, and which is current. Use it to find a kernel to reattach to, or to spot forgotten kernels worth stopping."
        return await c.list_kernels(host)

    async def stop_kernel(
        kernel:str='', # Kernel id (or unique prefix); empty stops the current kernel
    )->str:
        "Stop a kernel for good: its process ends and its state is gone. Explicitly created or attached kernels are stopped only this way - do it when the user is done with a kernel, and leave kernels running that the user wants to return to. (A kernel auto-created by `execute` also stops itself when the conversation ends or when `connect` moves elsewhere.)"
        return await c.stop(kernel)

    async def restart()->str:
        "Kill the current kernel's process and start a fresh one under the same id: `sys.modules` genuinely reset, all session state discarded. Use for a clean slate, after rebuilding a native extension, or after a reload left stale classes behind (symptoms: `isinstance` mysteriously failing, a class missing a method you know it has). Also works when `execute` is stuck. A kernel this conversation created gets startup.py re-run and inspectors reinstalled (the reply says so); an attached kernel restarts bare, as found."
        return await c.restart()

    async def interrupt()->str:
        "Interrupt the code the current kernel is running (SIGINT, i.e. KeyboardInterrupt): the in-flight `execute` returns with a KeyboardInterrupt traceback, and session state survives. Prefer this over `restart` when a call is merely taking too long. Only meaningful while an `execute` is running."
        return await c.interrupt()

    if not c.quiet:
        connect.__doc__ += " The startup output also appears in the reply."
        execute.__doc__ += " The connect banner - kernel id and startup output - is prepended to that first reply: read it."
    srv = MCPServer('clikernel', [connect, execute, list_kernels, stop_kernel, restart, interrupt], version=__version__)
    return srv


# %% ../nbs/01_mcp.ipynb #3b90f0e8
@call_parse
def main(
    quiet:store_true=False,  # Keep startup output out of replies; an auto-connecting `execute` returns just the result
):
    "The `clikernel-mcp` console script: the tools on stdio, state is one `Client`"
    async def _main():
        c = Client(quiet=quiet)
        try: await serve_stdio(mk_server(c))
        finally:
            if c.auto:   # an execute-made kernel is conversation-scoped; the gateway may already be gone
                try: await c.stop()
                except Exception as e: print(f'auto kernel stop failed: {e!r}', file=sys.stderr)
            await c.aclose()
    asyncio.run(_main())

