"""The MCP frontend: a stdio router over rustygate gateways

The frontend Claude Code launches per conversation. `Router` speaks stdio MCP to the harness and forwards to gateways: rustygate serves the tool surface itself, so the router defines no tools — it fetches the local gateway's `tools/list`, adds a `host` parameter to the kernel-selection tools, and forwards `tools/call` verbatim to the right gateway, ids intact so cancellation maps through. `main` serves a `Router` on stdio and ends every gateway session on the way out — the DELETE that stops each session's autoclose kernels, and the owned child gateway with them.

Docs: https://AnswerDotAI.github.io/clikernel/mcp.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_mcp.ipynb.

# %% auto #0
__all__ = ['HOST_PARAM', 'HOSTED', 'Router', 'main']

# %% ../nbs/01_mcp.ipynb #28c42902
import asyncio
from fastcore.utils import *
from fastcore.script import call_parse, store_true
from mcpmini.core import serve_stdio, jresp, jerr
from .core import Gateway, default_gateway, resolve, session_defaults
from . import __version__


# %% ../nbs/01_mcp.ipynb #76e2d782
HOST_PARAM = {'type': 'string', 'description': 'Gateway to target: a gateways.toml name, or empty for the default local gateway'}
HOSTED = ('list_kernels', 'use_kernel', 'create')

class Router:
    "Forward the harness's stdio MCP to rustygate gateways: one `Gateway` session per host, one current"
    def __init__(self,
        cfgdir=None,  # Config dir for `session_defaults` and `gateways.toml` (the standard one if None)
        quiet=False,  # Keep startup output out of replies?
    ):
        self.cfgdir,self.quiet,self.sessions,self.cur,self.child = cfgdir,quiet,{},'',None

    async def session(self, host=''):
        "The initialized `Gateway` for `host`, made on first use; empty means the default local gateway"
        if host not in self.sessions:
            if host:
                url, token, verify = resolve(host, self.cfgdir)
                self.sessions[host] = await Gateway(url, token, verify).initialize(session_defaults(self.cfgdir, self.quiet, local=False))
            else: self.sessions[host], self.child = await default_gateway(self.cfgdir, self.quiet)
        return self.sessions[host]

    async def aclose(self):
        "End every gateway session — stopping each one's autoclose kernels — then the owned child gateway"
        for s in self.sessions.values(): await s.aclose()
        if self.child: self.child.stop()


# %% ../nbs/01_mcp.ipynb #79da6a3e
@patch
async def tools(self:Router):
    "The local gateway's tools, with `host` added to the kernel-selection tools"
    ts = await (await self.session()).tools()
    for t in ts:
        if t['name'] in HOSTED: t['inputSchema'].setdefault('properties', {})['host'] = dict(HOST_PARAM)
    return ts

@patch
async def dispatch(self:Router, msg, requester=None):
    "One JSON-RPC message from the harness: initialize and ping answered here, the tool surface forwarded"
    method,id = msg.get('method'), msg.get('id')
    try:
        if method == 'initialize':
            info = (await self.session()).info
            return jresp(id, dict(protocolVersion=msg['params'].get('protocolVersion', '2025-06-18'), capabilities=dict(tools={}),
                serverInfo=dict(name='clikernel', version=__version__), instructions=info.get('instructions')))
        if id is None:
            if method == 'notifications/cancelled': await (await self.session(self.cur)).tr.send(msg)
            return None
        if method == 'ping': return jresp(id, {})
        if method == 'tools/list': return jresp(id, dict(tools=await self.tools()))
        if method == 'tools/call':
            args = msg['params'].setdefault('arguments', {})
            has_host = 'host' in args
            host = args.pop('host', '') or ''
            s = await self.session(host if has_host else self.cur)
            if has_host and msg['params']['name'] in ('use_kernel', 'create'): self.cur = host
            return await s.tr.send(msg)
        return jerr(id, -32601, f'method not found: {method}')
    except Exception as e: return None if id is None else jerr(id, -32603, str(e))

# %% ../nbs/01_mcp.ipynb #3b90f0e8
@call_parse
def main(
    quiet:store_true=False,  # Keep startup output out of replies
):
    "The `clikernel-mcp` console script: the router on stdio"
    async def _main():
        router = Router(quiet=quiet)
        try: await serve_stdio(router)
        finally: await router.aclose()
    asyncio.run(_main())

